services:
  web:
    build: ../
    container_name: stock-web
    ports:
      - '3000:3000'
    env_file:
      - ../.env.local
    networks:
      - stock-control-dev-network

networks:
  stock-control-dev-network:
    external: true
